spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/smartorder
    driver-class-name: org.mariadb.jdbc.Driver
    username: smartorder
    password: smartorder
#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      names: ${job.name:NONE}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: h2ju1004@gmail.com
    password: wmefsolhrcusfffu
    properties:
      mail:
        smtp:
          starttls:
            enable: true

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
