spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/smartorder
    driver-class-name: org.mariadb.jdbc.Driver
    username: smartorder
    password: smartorder

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # spring batch 자동실행 방지

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: h2ju1004@gmail.com
    password: wmefsolhrcusfffu
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  jwt:
    secret: c21hcnRvcmRlci1wcm9qZWN0LXJ5dXJlZXJ1LWp3dC1zZWNyZXQta2V5

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

api:
  key :